# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_SEMI_FINAL.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 555)
        MainWindow.setStyleSheet("#MainWindow{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"#home_widget{\n"
"background-color:rgb(58, 58, 58);\n"
"}\n"
"#msg_label{\n"
"    background-color: rgb(34,34,34);\n"
"    color: qlineargradient(spread:reflect, x1:0.334818, y1:0.278, x2:0.602273, y2:0.574, stop:0 rgba(255, 170, 0, 255), stop:0.994318 rgba(255, 255, 0, 255));\n"
"}\n"
"#grafic1_widget{\n"
"background-color:rgb(58, 58, 58);\n"
"}\n"
"#settings1_widget{\n"
"background-color:rgb(58, 58, 58);\n"
"}\n"
"#grafic2_widget{\n"
"background-color:rgb(58, 58, 58);\n"
"}\n"
"#settings2_widget{\n"
"background-color:rgb(58, 58, 58);\n"
"}\n"
"#home_btn{\n"
"background-color:rgb(0, 0, 0);\n"
"}\n"
"#option_btn{\n"
"background-color:rgb(0, 0, 0);\n"
"}\n"
"#settings_btn1{\n"
"background-color:rgb(0, 0, 0);\n"
"color:rgb(0, 162, 232);\n"
"}\n"
"#settings_btn2{\n"
"background-color:rgb(0, 0, 0);\n"
"color:rgb(0, 162, 232);\n"
"}\n"
"\n"
"#graf_btn1{\n"
"background-color:rgb(0, 0, 0);\n"
"color:rgb(0, 162, 232);\n"
"}\n"
"#graf_btn2{\n"
"background-color:rgb(0, 0, 0);\n"
"color:rgb(0, 162, 232);\n"
"}\n"
"#close_btn{\n"
"background-color:rgb(0, 0, 0);\n"
"}\n"
""
"#menu{\n"
"background-color:rgb(34, 34, 34);\n"
"}\n"
"")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(50, 0, 724, 51))
        font = QtGui.QFont()
        font.setFamily("ISOCTEUR")
        font.setPointSize(18)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:1, y1:0, x2:1, y2:0.506, stop:0.289773 rgba(48, 48, 48, 255), stop:0.75 rgba(59, 59, 59, 255));\n"
"color:qlineargradient(spread:reflect, x1:0.756, y1:0.755727, x2:1, y2:1, stop:0 rgba(0, 95, 143, 255), stop:1 rgba(0, 170, 255, 255))")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.menu = QtWidgets.QWidget(self.centralwidget)
        self.menu.setEnabled(True)
        self.menu.setGeometry(QtCore.QRect(0, 100, 52, 440))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setMinimumSize(QtCore.QSize(52, 410))
        self.menu.setMaximumSize(QtCore.QSize(190, 440))
        self.menu.setSizeIncrement(QtCore.QSize(0, 0))
        self.menu.setBaseSize(QtCore.QSize(0, 0))
        self.menu.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.menu.setStyleSheet("")
        self.menu.setObjectName("menu")
        self.settings_btn1 = QtWidgets.QPushButton(self.menu)
        self.settings_btn1.setGeometry(QtCore.QRect(0, 0, 191, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.settings_btn1.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("settings2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("settings.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.settings_btn1.setIcon(icon)
        self.settings_btn1.setIconSize(QtCore.QSize(30, 30))
        self.settings_btn1.setCheckable(False)
        self.settings_btn1.setAutoExclusive(False)
        self.settings_btn1.setObjectName("settings_btn1")
        self.line_29 = QtWidgets.QFrame(self.menu)
        self.line_29.setGeometry(QtCore.QRect(0, 50, 190, 2))
        self.line_29.setStyleSheet("background-color:rgb(0,162,232)")
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.line_30 = QtWidgets.QFrame(self.menu)
        self.line_30.setGeometry(QtCore.QRect(0, 100, 190, 2))
        self.line_30.setStyleSheet("background-color:rgb(0,162,232)")
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.close_btn = QtWidgets.QPushButton(self.menu)
        self.close_btn.setGeometry(QtCore.QRect(0, 380, 50, 51))
        self.close_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.close_btn.setStyleSheet("")
        self.close_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon1)
        self.close_btn.setIconSize(QtCore.QSize(30, 30))
        self.close_btn.setObjectName("close_btn")
        self.line_32 = QtWidgets.QFrame(self.menu)
        self.line_32.setGeometry(QtCore.QRect(0, 0, 190, 2))
        self.line_32.setStyleSheet("background-color:rgb(0,162,232)")
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.line_33 = QtWidgets.QFrame(self.menu)
        self.line_33.setGeometry(QtCore.QRect(188, 0, 3, 500))
        self.line_33.setMaximumSize(QtCore.QSize(3, 16777215))
        self.line_33.setStyleSheet("background-color:rgb(0,162,232)")
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.line_34 = QtWidgets.QFrame(self.menu)
        self.line_34.setGeometry(QtCore.QRect(0, 380, 50, 2))
        self.line_34.setStyleSheet("background-color:rgb(0,162,232)")
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.graf_btn1 = QtWidgets.QPushButton(self.menu)
        self.graf_btn1.setGeometry(QtCore.QRect(0, 100, 191, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.graf_btn1.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Graficos.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap("Graficos 2.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.graf_btn1.setIcon(icon2)
        self.graf_btn1.setIconSize(QtCore.QSize(30, 30))
        self.graf_btn1.setCheckable(False)
        self.graf_btn1.setChecked(False)
        self.graf_btn1.setAutoRepeat(False)
        self.graf_btn1.setAutoExclusive(False)
        self.graf_btn1.setObjectName("graf_btn1")
        self.line_35 = QtWidgets.QFrame(self.menu)
        self.line_35.setGeometry(QtCore.QRect(0, 150, 190, 2))
        self.line_35.setStyleSheet("background-color:rgb(0,162,232)")
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.graf_btn2 = QtWidgets.QPushButton(self.menu)
        self.graf_btn2.setGeometry(QtCore.QRect(0, 150, 191, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.graf_btn2.setFont(font)
        self.graf_btn2.setIcon(icon2)
        self.graf_btn2.setIconSize(QtCore.QSize(30, 30))
        self.graf_btn2.setCheckable(False)
        self.graf_btn2.setChecked(False)
        self.graf_btn2.setAutoRepeat(False)
        self.graf_btn2.setAutoExclusive(False)
        self.graf_btn2.setObjectName("graf_btn2")
        self.line_45 = QtWidgets.QFrame(self.menu)
        self.line_45.setGeometry(QtCore.QRect(0, 200, 190, 2))
        self.line_45.setStyleSheet("background-color:rgb(0,162,232)")
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.settings_btn2 = QtWidgets.QPushButton(self.menu)
        self.settings_btn2.setGeometry(QtCore.QRect(0, 50, 191, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.settings_btn2.setFont(font)
        self.settings_btn2.setIcon(icon)
        self.settings_btn2.setIconSize(QtCore.QSize(30, 30))
        self.settings_btn2.setCheckable(False)
        self.settings_btn2.setAutoExclusive(False)
        self.settings_btn2.setObjectName("settings_btn2")
        self.graf_btn1.lower()
        self.settings_btn1.lower()
        self.line_29.raise_()
        self.line_30.raise_()
        self.close_btn.raise_()
        self.line_32.raise_()
        self.line_33.raise_()
        self.line_34.raise_()
        self.line_35.raise_()
        self.graf_btn2.lower()
        self.line_45.raise_()
        self.settings_btn2.lower()
        self.home_btn = QtWidgets.QPushButton(self.centralwidget)
        self.home_btn.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.home_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.home_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("home.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("home2.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.home_btn.setIcon(icon3)
        self.home_btn.setIconSize(QtCore.QSize(30, 30))
        self.home_btn.setCheckable(False)
        self.home_btn.setAutoExclusive(False)
        self.home_btn.setObjectName("home_btn")
        self.option_btn = QtWidgets.QPushButton(self.centralwidget)
        self.option_btn.setGeometry(QtCore.QRect(0, 50, 51, 51))
        self.option_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.option_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("3barra.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.option_btn.setIcon(icon4)
        self.option_btn.setIconSize(QtCore.QSize(30, 30))
        self.option_btn.setCheckable(True)
        self.option_btn.setObjectName("option_btn")
        self.line_36 = QtWidgets.QFrame(self.centralwidget)
        self.line_36.setGeometry(QtCore.QRect(50, 0, 2, 600))
        self.line_36.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_36.setStyleSheet("background-color:rgb(0,162,232)")
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.line_37 = QtWidgets.QFrame(self.centralwidget)
        self.line_37.setGeometry(QtCore.QRect(0, 50, 51, 2))
        self.line_37.setStyleSheet("background-color:rgb(0,162,232)")
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.line_38 = QtWidgets.QFrame(self.centralwidget)
        self.line_38.setGeometry(QtCore.QRect(0, 0, 51, 2))
        self.line_38.setStyleSheet("background-color:rgb(0,162,232)")
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.settings1_widget = QtWidgets.QWidget(self.centralwidget)
        self.settings1_widget.setGeometry(QtCore.QRect(52, 102, 721, 431))
        self.settings1_widget.setStyleSheet("#Label_x1_0_A{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x1_A{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y1_0_A{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y1_A{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x2_0_A{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x2_A{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y2_0_A{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y2_A{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x3_0_A{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#aplicate1_btn{\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:0.596636, x2:0.5, y2:0.216, stop:0 rgba(0, 111, 111, 255), stop:1 rgba(0, 206, 206, 255));\n"
"    color: rgb(203, 203, 203);\n"
"}")
        self.settings1_widget.setObjectName("settings1_widget")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.settings1_widget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(30, 50, 116, 261))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setVerticalSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Label_x2_0_A = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.Label_x2_0_A.setObjectName("Label_x2_0_A")
        self.gridLayout_7.addWidget(self.Label_x2_0_A, 2, 0, 1, 1)
        self.y1_0_A = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.y1_0_A.setMaximumSize(QtCore.QSize(35, 16777215))
        self.y1_0_A.setObjectName("y1_0_A")
        self.gridLayout_7.addWidget(self.y1_0_A, 1, 2, 1, 1)
        self.x2_0_A = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.x2_0_A.setMaximumSize(QtCore.QSize(35, 16777215))
        self.x2_0_A.setObjectName("x2_0_A")
        self.gridLayout_7.addWidget(self.x2_0_A, 2, 2, 1, 1)
        self.x1_0_A = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.x1_0_A.setMaximumSize(QtCore.QSize(35, 16777215))
        self.x1_0_A.setText("")
        self.x1_0_A.setObjectName("x1_0_A")
        self.gridLayout_7.addWidget(self.x1_0_A, 0, 2, 1, 1)
        self.Label_x1_0_A = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.Label_x1_0_A.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_x1_0_A.setObjectName("Label_x1_0_A")
        self.gridLayout_7.addWidget(self.Label_x1_0_A, 0, 0, 1, 1)
        self.Label_y1_0_A = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.Label_y1_0_A.setObjectName("Label_y1_0_A")
        self.gridLayout_7.addWidget(self.Label_y1_0_A, 1, 0, 1, 1)
        self.y2_0_A = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.y2_0_A.setMaximumSize(QtCore.QSize(35, 16777215))
        self.y2_0_A.setObjectName("y2_0_A")
        self.gridLayout_7.addWidget(self.y2_0_A, 3, 2, 1, 1)
        self.Label_y2_0_A = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.Label_y2_0_A.setMaximumSize(QtCore.QSize(30, 16777215))
        self.Label_y2_0_A.setObjectName("Label_y2_0_A")
        self.gridLayout_7.addWidget(self.Label_y2_0_A, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 2, 1, 1, 1)
        self.IMG_MEC1 = QtWidgets.QLabel(self.settings1_widget)
        self.IMG_MEC1.setGeometry(QtCore.QRect(170, 50, 311, 251))
        self.IMG_MEC1.setText("")
        self.IMG_MEC1.setPixmap(QtGui.QPixmap("mecanismo.PNG"))
        self.IMG_MEC1.setScaledContents(True)
        self.IMG_MEC1.setObjectName("IMG_MEC1")
        self.aplicate1_btn = QtWidgets.QPushButton(self.settings1_widget)
        self.aplicate1_btn.setGeometry(QtCore.QRect(160, 350, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(11)
        self.aplicate1_btn.setFont(font)
        self.aplicate1_btn.setStyleSheet("")
        self.aplicate1_btn.setObjectName("aplicate1_btn")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.settings1_widget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(510, 50, 113, 261))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Label_x2_A = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.Label_x2_A.setObjectName("Label_x2_A")
        self.gridLayout_9.addWidget(self.Label_x2_A, 2, 0, 1, 1)
        self.y1_A = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.y1_A.setMaximumSize(QtCore.QSize(35, 16777215))
        self.y1_A.setObjectName("y1_A")
        self.gridLayout_9.addWidget(self.y1_A, 1, 2, 1, 1)
        self.x2_A = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.x2_A.setMaximumSize(QtCore.QSize(35, 16777215))
        self.x2_A.setObjectName("x2_A")
        self.gridLayout_9.addWidget(self.x2_A, 2, 2, 1, 1)
        self.x1_A = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.x1_A.setMaximumSize(QtCore.QSize(35, 16777215))
        self.x1_A.setText("")
        self.x1_A.setObjectName("x1_A")
        self.gridLayout_9.addWidget(self.x1_A, 0, 2, 1, 1)
        self.Label_x1_A = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.Label_x1_A.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_x1_A.setObjectName("Label_x1_A")
        self.gridLayout_9.addWidget(self.Label_x1_A, 0, 0, 1, 1)
        self.Label_y1_A = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.Label_y1_A.setObjectName("Label_y1_A")
        self.gridLayout_9.addWidget(self.Label_y1_A, 1, 0, 1, 1)
        self.y2_A = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.y2_A.setMaximumSize(QtCore.QSize(35, 16777215))
        self.y2_A.setObjectName("y2_A")
        self.gridLayout_9.addWidget(self.y2_A, 3, 2, 1, 1)
        self.Label_y2_A = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.Label_y2_A.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Label_y2_A.setObjectName("Label_y2_A")
        self.gridLayout_9.addWidget(self.Label_y2_A, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 2, 1, 1, 1)
        self.grafic1_widget = QtWidgets.QWidget(self.centralwidget)
        self.grafic1_widget.setGeometry(QtCore.QRect(52, 102, 721, 431))
        self.grafic1_widget.setStyleSheet("#update_graf1_btn{\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:0.596636, x2:0.5, y2:0.216, stop:0 rgba(0, 111, 111, 255), stop:1 rgba(0, 206, 206, 255));\n"
"    color: rgb(203, 203, 203);\n"
"}\n"
"#label_cuadro_1{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:4px outset rgb(102, 102, 102);\n"
"}")
        self.grafic1_widget.setObjectName("grafic1_widget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.grafic1_widget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(160, 40, 401, 291))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.grafica_uno = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.grafica_uno.setContentsMargins(0, 0, 0, 0)
        self.grafica_uno.setObjectName("grafica_uno")
        self.update_graf1_btn = QtWidgets.QPushButton(self.grafic1_widget)
        self.update_graf1_btn.setGeometry(QtCore.QRect(190, 360, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(11)
        self.update_graf1_btn.setFont(font)
        self.update_graf1_btn.setStyleSheet("")
        self.update_graf1_btn.setObjectName("update_graf1_btn")
        self.settings2_widget = QtWidgets.QWidget(self.centralwidget)
        self.settings2_widget.setGeometry(QtCore.QRect(52, 102, 721, 431))
        self.settings2_widget.setStyleSheet("#Label_x1_0{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x1{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y1_0{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y1{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x2_0{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x2{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y2_0{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y2{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x3_0{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x3{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y3_0{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y3{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x4_0{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_x4{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y4_0{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#Label_y4{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#aplicate2_btn{\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:0.596636, x2:0.5, y2:0.216, stop:0 rgba(0, 111, 111, 255), stop:1 rgba(0, 206, 206, 255));\n"
"    color: rgb(203, 203, 203);\n"
"}")
        self.settings2_widget.setObjectName("settings2_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.settings2_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 50, 136, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Label_x1_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_x1_0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_x1_0.setObjectName("Label_x1_0")
        self.gridLayout.addWidget(self.Label_x1_0, 0, 0, 1, 1)
        self.y1_0 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.y1_0.setObjectName("y1_0")
        self.gridLayout.addWidget(self.y1_0, 1, 2, 1, 1)
        self.x4_0 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.x4_0.setObjectName("x4_0")
        self.gridLayout.addWidget(self.x4_0, 6, 2, 1, 1)
        self.Label_x4_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_x4_0.setObjectName("Label_x4_0")
        self.gridLayout.addWidget(self.Label_x4_0, 6, 0, 1, 1)
        self.Label_x3_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_x3_0.setObjectName("Label_x3_0")
        self.gridLayout.addWidget(self.Label_x3_0, 4, 0, 1, 1)
        self.Label_y2_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_y2_0.setObjectName("Label_y2_0")
        self.gridLayout.addWidget(self.Label_y2_0, 3, 0, 1, 1)
        self.x3_0 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.x3_0.setText("")
        self.x3_0.setObjectName("x3_0")
        self.gridLayout.addWidget(self.x3_0, 4, 2, 1, 1)
        self.y2_0 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.y2_0.setObjectName("y2_0")
        self.gridLayout.addWidget(self.y2_0, 3, 2, 1, 1)
        self.Label_y1_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_y1_0.setObjectName("Label_y1_0")
        self.gridLayout.addWidget(self.Label_y1_0, 1, 0, 1, 1)
        self.Label_x2_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_x2_0.setObjectName("Label_x2_0")
        self.gridLayout.addWidget(self.Label_x2_0, 2, 0, 1, 1)
        self.x2_0 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.x2_0.setObjectName("x2_0")
        self.gridLayout.addWidget(self.x2_0, 2, 2, 1, 1)
        self.x1_0 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.x1_0.setText("")
        self.x1_0.setObjectName("x1_0")
        self.gridLayout.addWidget(self.x1_0, 0, 2, 1, 1)
        self.Label_y4_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_y4_0.setObjectName("Label_y4_0")
        self.gridLayout.addWidget(self.Label_y4_0, 7, 0, 1, 1)
        self.y3_0 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.y3_0.setObjectName("y3_0")
        self.gridLayout.addWidget(self.y3_0, 5, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        self.Label_y3_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_y3_0.setObjectName("Label_y3_0")
        self.gridLayout.addWidget(self.Label_y3_0, 5, 0, 1, 1)
        self.y4_0 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.y4_0.setObjectName("y4_0")
        self.gridLayout.addWidget(self.y4_0, 7, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.settings2_widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(500, 50, 124, 261))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Label_x3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_x3.setObjectName("Label_x3")
        self.gridLayout_2.addWidget(self.Label_x3, 4, 0, 1, 1)
        self.Label_y3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_y3.setObjectName("Label_y3")
        self.gridLayout_2.addWidget(self.Label_y3, 5, 0, 1, 1)
        self.Label_y4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_y4.setObjectName("Label_y4")
        self.gridLayout_2.addWidget(self.Label_y4, 7, 0, 1, 1)
        self.x1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x1.setText("")
        self.x1.setObjectName("x1")
        self.gridLayout_2.addWidget(self.x1, 0, 2, 1, 1)
        self.x3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x3.setText("")
        self.x3.setObjectName("x3")
        self.gridLayout_2.addWidget(self.x3, 4, 2, 1, 1)
        self.x4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x4.setObjectName("x4")
        self.gridLayout_2.addWidget(self.x4, 6, 2, 1, 1)
        self.y1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.y1.setObjectName("y1")
        self.gridLayout_2.addWidget(self.y1, 1, 2, 1, 1)
        self.y2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.y2.setObjectName("y2")
        self.gridLayout_2.addWidget(self.y2, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 4, 1, 1, 1)
        self.y4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.y4.setObjectName("y4")
        self.gridLayout_2.addWidget(self.y4, 7, 2, 1, 1)
        self.Label_y1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_y1.setObjectName("Label_y1")
        self.gridLayout_2.addWidget(self.Label_y1, 1, 0, 1, 1)
        self.Label_y2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_y2.setObjectName("Label_y2")
        self.gridLayout_2.addWidget(self.Label_y2, 3, 0, 1, 1)
        self.Label_x2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_x2.setObjectName("Label_x2")
        self.gridLayout_2.addWidget(self.Label_x2, 2, 0, 1, 1)
        self.y3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.y3.setObjectName("y3")
        self.gridLayout_2.addWidget(self.y3, 5, 2, 1, 1)
        self.x2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x2.setObjectName("x2")
        self.gridLayout_2.addWidget(self.x2, 2, 2, 1, 1)
        self.Label_x1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_x1.setObjectName("Label_x1")
        self.gridLayout_2.addWidget(self.Label_x1, 0, 0, 1, 1)
        self.Label_x4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_x4.setObjectName("Label_x4")
        self.gridLayout_2.addWidget(self.Label_x4, 6, 0, 1, 1)
        self.IMG_MEC2 = QtWidgets.QLabel(self.settings2_widget)
        self.IMG_MEC2.setGeometry(QtCore.QRect(170, 50, 311, 261))
        self.IMG_MEC2.setText("")
        self.IMG_MEC2.setPixmap(QtGui.QPixmap("mecanismo2.png"))
        self.IMG_MEC2.setScaledContents(True)
        self.IMG_MEC2.setObjectName("IMG_MEC2")
        self.aplicate2_btn = QtWidgets.QPushButton(self.settings2_widget)
        self.aplicate2_btn.setGeometry(QtCore.QRect(160, 350, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(11)
        self.aplicate2_btn.setFont(font)
        self.aplicate2_btn.setStyleSheet("")
        self.aplicate2_btn.setObjectName("aplicate2_btn")
        self.msg_label = QtWidgets.QLabel(self.centralwidget)
        self.msg_label.setGeometry(QtCore.QRect(52, 52, 721, 49))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(15)
        self.msg_label.setFont(font)
        self.msg_label.setStyleSheet("")
        self.msg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.msg_label.setObjectName("msg_label")
        self.home_widget = QtWidgets.QWidget(self.centralwidget)
        self.home_widget.setGeometry(QtCore.QRect(52, 102, 721, 431))
        self.home_widget.setStyleSheet("#logo_mecatronica{\n"
"border-color: rgb(122, 122, 122);\n"
"\n"
"}\n"
"#label_list{\n"
"    \n"
"    \n"
"    background-color: rgb(63, 125, 188);\n"
"}\n"
"\n"
"#label_int{\n"
"    background-color: rgb(63, 125, 188);\n"
"}\n"
"")
        self.home_widget.setObjectName("home_widget")
        self.label_28 = QtWidgets.QLabel(self.home_widget)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 701, 51))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: qlineargradient(spread:reflect, x1:0.334818, y1:0.278, x2:0.602273, y2:0.574, stop:0 rgba(217, 217, 217, 255), stop:1 rgba(156, 156, 156, 255));\n"
"background-color:qlineargradient(spread:reflect, x1:1, y1:1, x2:0.438, y2:0.409, stop:0.0454545 rgba(0, 69, 104, 255), stop:1 rgba(57, 113, 170, 255));\n"
"border: 1px solid rgb(0, 131, 197);\n"
"\n"
"")
        self.label_28.setTextFormat(QtCore.Qt.AutoText)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setIndent(-1)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.home_widget)
        self.label_29.setGeometry(QtCore.QRect(53, 70, 341, 221))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_int = QtWidgets.QLabel(self.home_widget)
        self.label_int.setGeometry(QtCore.QRect(370, 100, 271, 51))
        self.label_int.setFrameShape(QtWidgets.QFrame.Box)
        self.label_int.setLineWidth(2)
        self.label_int.setTextFormat(QtCore.Qt.RichText)
        self.label_int.setObjectName("label_int")
        self.logo_mecatronica = QtWidgets.QLabel(self.home_widget)
        self.logo_mecatronica.setGeometry(QtCore.QRect(50, 100, 301, 301))
        self.logo_mecatronica.setFrameShape(QtWidgets.QFrame.Box)
        self.logo_mecatronica.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_mecatronica.setLineWidth(5)
        self.logo_mecatronica.setText("")
        self.logo_mecatronica.setPixmap(QtGui.QPixmap("logo_UNT.png"))
        self.logo_mecatronica.setScaledContents(True)
        self.logo_mecatronica.setObjectName("logo_mecatronica")
        self.label_list = QtWidgets.QLabel(self.home_widget)
        self.label_list.setGeometry(QtCore.QRect(370, 148, 271, 181))
        self.label_list.setFrameShape(QtWidgets.QFrame.Box)
        self.label_list.setLineWidth(2)
        self.label_list.setTextFormat(QtCore.Qt.PlainText)
        self.label_list.setObjectName("label_list")
        self.grafic2_widget = QtWidgets.QWidget(self.centralwidget)
        self.grafic2_widget.setGeometry(QtCore.QRect(52, 102, 721, 431))
        self.grafic2_widget.setStyleSheet("#update_graf2_btn{\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:0.596636, x2:0.5, y2:0.216, stop:0 rgba(0, 111, 111, 255), stop:1 rgba(0, 206, 206, 255));\n"
"    color: rgb(203, 203, 203);\n"
"}\n"
"#label_cuadro2{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:4px outset rgb(102, 102, 102);\n"
"}")
        self.grafic2_widget.setObjectName("grafic2_widget")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.grafic2_widget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(160, 40, 401, 291))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.grafica_dos = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.grafica_dos.setContentsMargins(0, 0, 0, 0)
        self.grafica_dos.setObjectName("grafica_dos")
        self.update_graf2_btn = QtWidgets.QPushButton(self.grafic2_widget)
        self.update_graf2_btn.setGeometry(QtCore.QRect(190, 360, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(11)
        self.update_graf2_btn.setFont(font)
        self.update_graf2_btn.setStyleSheet("")
        self.update_graf2_btn.setObjectName("update_graf2_btn")
        self.label_20.raise_()
        self.menu.raise_()
        self.home_btn.lower()
        self.option_btn.raise_()
        self.line_36.raise_()
        self.line_37.raise_()
        self.line_38.raise_()
        self.home_widget.raise_()
        #MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        #MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.close_btn.clicked.connect(MainWindow.close)
        self.graf_btn1.clicked.connect(self.grafic1_widget.raise_)
        self.settings_btn1.clicked.connect(self.settings1_widget.raise_)
        self.settings_btn2.clicked.connect(self.settings2_widget.raise_)
        self.home_btn.clicked.connect(self.home_widget.raise_)
        self.graf_btn2.clicked.connect(self.grafic2_widget.raise_)
        
        self.graf_btn1.clicked.connect(lambda: self.cambiar_menu("Grafica del mecanismo 1"))
        self.settings_btn1.clicked.connect(lambda: self.cambiar_menu("Configuración del mecanismo 1"))
        self.settings_btn2.clicked.connect(lambda: self.cambiar_menu("Configuración del mecanismo 2"))
        self.home_btn.clicked.connect(lambda: self.cambiar_menu("Ventana principal"))
        self.graf_btn2.clicked.connect(lambda: self.cambiar_menu("Grafica del mecanismo 2"))
        self.option_btn.clicked.connect(lambda: self.cambiar_menu(""))

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_20.setText(_translate("MainWindow", "LABORATORIO 2"))
        self.settings_btn1.setText(_translate("MainWindow", "           Configuración 1       "))
        self.graf_btn1.setText(_translate("MainWindow", "                  Gráfica 1             "))
        self.graf_btn2.setText(_translate("MainWindow", "                  Gráfica 2             "))
        self.settings_btn2.setText(_translate("MainWindow", "           Configuración 2       "))
        self.Label_x2_0_A.setText(_translate("MainWindow", "X2_0"))
        self.Label_x1_0_A.setText(_translate("MainWindow", "X1_0"))
        self.Label_y1_0_A.setText(_translate("MainWindow", "Y1_0"))
        self.Label_y2_0_A.setText(_translate("MainWindow", "Y2_0"))
        self.aplicate1_btn.setText(_translate("MainWindow", "APLICAR"))
        self.Label_x2_A.setText(_translate("MainWindow", "X2"))
        self.Label_x1_A.setText(_translate("MainWindow", "X1"))
        self.Label_y1_A.setText(_translate("MainWindow", "Y1"))
        self.Label_y2_A.setText(_translate("MainWindow", "Y2   "))
        self.update_graf1_btn.setText(_translate("MainWindow", "ACTUALIZAR GRÁFICO"))
        self.Label_x1_0.setText(_translate("MainWindow", "X1_0"))
        self.Label_x4_0.setText(_translate("MainWindow", "X4_0"))
        self.Label_x3_0.setText(_translate("MainWindow", "X3_0"))
        self.Label_y2_0.setText(_translate("MainWindow", "Y2_0"))
        self.Label_y1_0.setText(_translate("MainWindow", "Y1_0"))
        self.Label_x2_0.setText(_translate("MainWindow", "X2_0"))
        self.Label_y4_0.setText(_translate("MainWindow", "Y4_0"))
        self.Label_y3_0.setText(_translate("MainWindow", "Y3_0"))
        self.Label_x3.setText(_translate("MainWindow", "X3"))
        self.Label_y3.setText(_translate("MainWindow", "Y3"))
        self.Label_y4.setText(_translate("MainWindow", "Y4"))
        self.Label_y1.setText(_translate("MainWindow", "Y1"))
        self.Label_y2.setText(_translate("MainWindow", "Y2"))
        self.Label_x2.setText(_translate("MainWindow", "X2"))
        self.Label_x1.setText(_translate("MainWindow", "X1"))
        self.Label_x4.setText(_translate("MainWindow", "X4"))
        self.aplicate2_btn.setText(_translate("MainWindow", "APLICAR"))
        self.msg_label.setText(_translate("MainWindow", "Ventana principal"))
        self.label_28.setText(_translate("MainWindow", "PRESENTACIÓN"))
        self.label_int.setText(_translate("MainWindow", "INTEGRANTES:"))
        self.label_list.setText(_translate("MainWindow", "Cabrera Gallardo Carlos Gabriel\n"
"\n"
"Corcuera Araujo Carlos Bitner\n"
"\n"
"Fernandez Reyes José María\n"
"\n"
"Montoya Herrera Marcelo José\n"
"\n"
"Olórtegui Revoredo Josué Eduardo\n"
"\n"
"Rocha Montoya Carlos Adrián\n"))
        self.update_graf2_btn.setText(_translate("MainWindow", "ACTUALIZAR GRÁFICO"))
        
    def cambiar_menu(self,text):
     #  self.menu.raise_()
        if self.option_btn.isChecked():
            self.menu.raise_()
            self.menu.setGeometry(QtCore.QRect(0, 100, 190, 500))
            self.line_36.raise_()
        else:
            self.menu.lower()
            self.menu.setGeometry(QtCore.QRect(0, 100, 52, 500))
        if text == "":
            pass
        else:
            self.msg_label.setText(text)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
